name: projectHY
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cmake # for compiling atari-py
  - cudatoolkit
  - cython
  - ffmpeg=4.2.2 # version 4.3 doesn't work with x264 through gym.Monitor
  - freetype
  - graphviz
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - networkx
  - nltk # for torchtext SST dataset
  - nodejs
  - numpy
  - numba
  - opencv
  - pandas
  - pillow
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz # for graphviz on Windows
  - python=3.8.6
  - pytorch=1.6.0
  - rise
  - scikit-learn
  - scipy
  - spacy-model-en_core_web_sm=2.3
  - spacy=2.3
  - swig # for box2d on Windows
  - tqdm
  - x264
  - pip
  - pip:
    - torchviz
    - nbmerge
    - gym
    - atari-py
    - box2d-py
    - pyvista==0.29.0
    - matplotlib==3.1.3
    - scipy==1.4.1
    - numpy==1.18.1
    - scikit_learn==0.24.1
